config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/bike-shop' => 'accessories#index'

  get '/dashboard' => 'users#dashboard'
  get '/trips-dashboard' => 'trips#dashboard'
  get '/stations-dashboard' => 'stations#dashboard'
  get '/conditions-dashboard' => 'conditions#dashboard'

  delete '/carts' => 'carts#destroy'
  post '/carts' => 'carts#create'
  put '/carts' => 'carts#update'

  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:show, :create]
  resources :carts, only: [:create, :index]
  resources :stations, only: [:index]
  resources :trips, only: [:index, :show]
  resources :conditions, only: [:index, :show]
	resources :accessories, only: :show

  namespace :admin do
    resources :stations, except: [:index, :show]
    resources :trips, except: [:index, :show]
    resources :conditions, except: [:index, :show]
    resources :accessories, only: [:create, :edit, :update]
    resources :orders, only: [:edit, :update]
    get '/dashboard' => 'users#dashboard'
    get '/bike-shop' => 'accessories#index'
    get '/bike-shop/new' => 'accessories#new'
  end

   get '/:id', to: 'stations#show', as: :station
end

app/models/station.rb
class Station < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :name, :dock_count, :city, :installation_date
  validates_uniqueness_of :name
  validates_uniqueness_of :slug

  validates_numericality_of :dock_count, :greater_than_or_equal_to => 0
  has_many :start_trips, class_name: 'Trip', foreign_key: 'start_station_id', dependent: :destroy
  has_many :end_trips, class_name: 'Trip', foreign_key: 'end_station_id', dependent: :destroy

  def to_param
    slug
  end

  def should_generate_new_friendly_id?
    slug.blank? || self.name_changed?
  end

  def self.stations_total_count
    count
  end

  def self.average_docks
    average(:dock_count)
  end

  def self.most_bikes
    maximum(:dock_count)
  end

  def self.most_bikes_station
    Station.where(dock_count: most_bikes).pluck(:name)
  end

  def self.fewest_bikes
    minimum(:dock_count)
  end

  def self.fewest_bikes_station
    Station.where(dock_count: fewest_bikes).pluck(:name)
  end

  def self.newest_installation
    order(installation_date: :desc).first.name
  end

  def self.oldest_installation
    order(:installation_date).first.name
  end

  def self.max_starting_station
    select("name, count(trips.id) as count").
    joins('join trips on trips.start_station_id = stations.id').
    group('stations.id').order('count desc').
    limit(1).first.name
  end

  def self.max_ending_station
    select("name, count(trips.id) as count").
    joins('join trips on trips.end_station_id = stations.id').
    group('stations.id').order('count desc').
    limit(1).first.name
  end

  def rides_started
    start_trips.count
  end

  def rides_ended
    end_trips.count
  end

  def most_trips_to
     station = Station.select(:name)
    .joins("join trips on trips.end_station_id = stations.id")
    .where("trips.start_station_id = ?", id)
    .group(:id)
    .order("count(end_station_id) desc")
     station.first.name unless station.first.nil?
  end

  def most_trips_from
    station = Station.select(:name)
    .joins("join trips on trips.start_station_id = stations.id")
    .where("trips.end_station_id = ?", id)
    .group(:id)
    .order("count(start_station_id) desc")
     station.first.name unless station.first.nil?
  end

  def date_with_highest_number
    station = start_trips.select("trips.start_date, count(trips.start_station_id) as count")
    .where("trips.start_station_id = ?", id)
    .group(:start_date)
    .order("count")
    station.last.start_date unless station.last.nil?
  end

  def frequent_zip_code
    station = start_trips.select('trips.zip_code, count(trips.id) as count')
    .group('trips.zip_code')
    .order('count')
    station.last.zip_code unless station.last.nil?
  end

  def frequent_bike_id
    station = start_trips.select('bike_id, count(start_station_id) as count')
    .group(:bike_id)
    .order('count')
    station.last.bike_id unless station.last.nil?
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController

  def new
    @station = Station.new
  end

  def create
    @station = Station.create(station_params)
    if @station.save
      flash[:notice] = "Station #{@station.name} successfully created!"
      redirect_to station_path(@station)
    else
      flash[:alert] = 'Oops, something went wrong, please try again!'
      render :new
    end
  end

  def edit
    @station = Station.find_by(slug: params[:id])
  end

  def update
    @station = Station.find_by(slug: params[:id])
    @station.update(station_params)
    if @station.save
      @station.should_generate_new_friendly_id?
      flash[:notice] = "Successfully updated station #{@station.name}."
      redirect_to station_path(@station)
    else
      flash[:alert] = 'Oops, something went wrong, please try again!'
      render :edit
    end
  end

  def destroy
    station = Station.find_by(slug: params[:id])
    station.destroy
    flash[:notice] = "Station successfully deleted."
    redirect_to stations_path
  end

  private
    def station_params
      params.require(:station).permit(:name, :dock_count, :city, :installation_date)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show]

  def dashboard
    @stations_count = Station.stations_total_count
    @average_docks = Station.average_docks
    @max_bikes = Station.most_bikes
    @station_max_bikes = Station.most_bikes_station
    @min_bikes = Station.fewest_bikes
    @station_min_bikes = Station.fewest_bikes_station
    @newest_station = Station.newest_installation
    @oldest_station = Station.oldest_installation
  end

  def index
    @stations = Station.all
  end

  def show
  end

  private
    def set_station
      @station = Station.friendly.find(params[:id])
    end
end

app/views/stations/dashboard.html.erb
<h3 class="text-center"> Stations Dashboard </h3>

<p class="text-center"><%= link_to "Back to All Stations", stations_path %></p>
</br>

<div class="container">
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-12">

      <table class="table">
        <tbody>
          <tr id="total-stations">
            <th> Total count of stations</th>
            <td> <%= @stations_count %></td>
          </tr>
          <tr id="average-bikes">
            <th>Average bikes available per station</th>
            <td><%= @average_docks.round(2) %></td>
          </tr>
          <tr id="recently-installed">
            <th>Most recently installed station</th>
            <td><%= @newest_station %></td>
          </tr>
          <tr id="oldest-station">
            <th>Oldest station</th>
            <td><%= @oldest_station %></td>
          </tr>
        </tbody>
      </table>

      </br>
      <h4 class="text-center"> Stations with the most rides </h4>
      </br>

      <table class="table" id="most-rides-table">
        <thead>
          <tr>
            <th scope="col">Station</th>
            <th scope="col">Rides</th>
          </tr>
        </thead>
        <tbody>
          <% @station_max_bikes.each do |station| %>
          <tr>
            <td><%= station %></td>
            <td><%= @max_bikes %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      </br>
      <h4 class="text-center"> Stations with the least rides </h4>
      </br>

      <table class="table" id="fewest-rides-table">
        <thead>
          <tr>
            <th scope="col">Station</th>
            <th scope="col">Rides</th>
          </tr>
        </thead>
        <tbody>
          <% @station_min_bikes.each do |station| %>
          <tr>
            <td><%= station %></td>
            <td><%= @min_bikes %></td>
          </tr>
          <% end %>
        </tbody>
      </table>



    </div>
    <div class="col-sm"></div>
  </div>
</div>

app/views/stations/index.html.erb
<h1 class='text-center'>All Stations</h1>

<p class='text-center'><%= link_to 'Stations Dashboard', stations_dashboard_path %></p>

<% if current_admin? %>
  <p class='text-center'><%= link_to 'Create A New Station', new_admin_station_path %></p>
<% end %>



<table class="table">
  <thead>
    <tr>
      <th scope="col">Station</th>
      <th scope="col">Dock Count</th>
      <th scope="col">City</th>
      <th scope="col">Installed</th>
    </tr>
  </thead>
  <tbody>
    <% @stations.each do |station| %>
    <tr id="station-<%= station.id %>">
      <th scope="row"><%= link_to station.name, station_path(station)%></th>
      <td><%= station.dock_count %></td>
      <td><%= station.city %></td>
      <td><%= station.installation_date %></td>
      <% if current_admin? %>
        <td><%= link_to 'Edit', edit_admin_station_path(station) %></td>
        <td><%= link_to 'Delete', admin_station_path(station), method: :delete %></td>
      <% end %>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/stations/show.html.erb
<h1 class='text-center'><%= @station.name %></h1>

<p class='text-center'><%= link_to "Back to All Stations", stations_path %></p>

<div class="container">
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-12">
      <table class="table">
        <tbody>
          <tr id="dock-count">
            <td>Dock Count</td>
            <td><%= @station.dock_count %></td>
          </tr>
          <tr>
            <td>City</td>
            <td><%= @station.city %></td>
          </tr>
          <tr>
            <td>Date of Installation</td>
            <td><%= @station.installation_date %></td>
          </tr>
          <% if current_user? %>
          <tr id='rides-started'>
            <td>Number of rides started at this station</td>
            <td><%= @station.rides_started %></td>
          </tr>
          <tr id='rides-ended'>
            <td>Number of rides ended at this station</td>
            <td><%= @station.rides_ended %></td>
          </tr>
          <tr id='most-frequent-destination'>
            <td>Most frequent destination station</td>
            <td><%= @station.most_trips_to %></td>
          </tr>
          <tr id='most-frequent-origination'>
            <td>Most frequent origination station</td>
            <td><%= @station.most_trips_from %></td>
          </tr>
          <tr id='highest-date'>
            <td>Date with the highest number of trips started at this station</td>
            <td><%= @station.date_with_highest_number.strftime("%F") unless @station.date_with_highest_number.nil? %> </td>
          </tr>
          <tr id='frequent-zip'>
            <td>Most frequent zip code for users starting trips at this station</td>
            <td><%= @station.frequent_zip_code %></td>
          </tr>
          <tr id='frequent-bike'>
            <td>Bike ID most frequently starting a trip at this station</td>
            <td> <%= @station.frequent_bike_id %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <% if current_admin? %>
        <%= link_to 'Edit', edit_admin_station_path(@station) %>
        <%= link_to 'Delete', admin_station_path(@station), method: :delete %>
      <% end %>

    </div>
    <div class="col-sm"></div>
  </div>
</div>