config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/bike-shop' => 'accessories#index'

  get '/dashboard' => 'users#dashboard'
  get '/trips-dashboard' => 'trips#dashboard'
  get '/stations-dashboard' => 'stations#dashboard'
  get '/conditions-dashboard' => 'conditions#dashboard'

  delete '/carts' => 'carts#destroy'
  post '/carts' => 'carts#create'
  put '/carts' => 'carts#update'

  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:show, :create]
  resources :carts, only: [:create, :index]
  resources :stations, only: [:index]
  resources :trips, only: [:index, :show]
  resources :conditions, only: [:index, :show]
	resources :accessories, only: :show

  namespace :admin do
    resources :stations, except: [:index, :show]
    resources :trips, except: [:index, :show]
    resources :conditions, except: [:index, :show]
    resources :accessories, only: [:create, :edit, :update]
    resources :orders, only: [:edit, :update]
    get '/dashboard' => 'users#dashboard'
    get '/bike-shop' => 'accessories#index'
    get '/bike-shop/new' => 'accessories#new'
  end

   get '/:id', to: 'stations#show', as: :station
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  validates_presence_of :description, :price
  validates :title, uniqueness: true, presence: true
  validates_numericality_of :price, greater_than_or_equal_to: 0
  has_many :order_accessories
  has_many :orders, through: :order_accessories
  enum status: [:active, :retired]
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  def index
    @accessories = Accessory.all
  end

  def show
   @accessory = Accessory.find(params[:id])
  end
end

app/controllers/admin/accessories_controller.rb
class Admin::AccessoriesController< Admin::BaseController
  def index
    @accessories = Accessory.all
  end

  def new
    @accessory = Accessory.new
  end

  def create
    @accessory = Accessory.create(accessory_params)
    if @accessory.save
      flash[:notice] = "Successfully Created #{@accessory.title}"
      redirect_to accessory_path(@accessory)
    else
      flash[:alert] = 'Oops, something went wrong, please try again!'
      render :new 
    end
  end

  def edit
    @accessory = Accessory.find(params[:id])
  end

  def update
    @accessory = Accessory.find(params[:id])
    @accessory.update(accessory_params)
    if @accessory.save
      flash[:notice] = "Successfully updated accessory."
      redirect_to admin_bike_shop_path
    else
      flash[:alert] = "Something went wrong, please try again."
      render :edit
    end
  end

  private
  def accessory_params
    params.require(:accessory).permit(:title, :description, :price, :status)
  end

end

app/views/admin/accessories/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm">

      <%= form_for [:admin, @accessory] do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        </br>

        <%= f.label :description %>
        <%= f.text_field :description %>
        </br>

        <%= f.label :price %>
        <%= f.text_field :price %>
        </br>

        <%= f.label :status %>
        <%= f.select :status, options_for_select(["active", "retired"]) %>
        </br>
        <%= f.submit %>
      <% end %>
    </div>
    <div class="col-sm"></div>
  </div>
</div>

app/views/admin/accessories/edit.html.erb
<h1 class='text-center'>Edit an Accessory</h1>

<%= render partial: "form" %>

app/views/admin/accessories/index.html.erb
<h1 class='text-center'>Bike Accessories</h1>

<p class='text-center'><%= link_to 'Create A New Accessory', admin_bike_shop_new_path %></p>




<div class="container">
  <% @accessories.each_slice(4) do |item_group| %>
  <div class="row">
    <% item_group.each do |item| %>
    <div class="card" style="width: 16rem; margin: 1%;">
      <%= image_tag(item.image, :size => "100x180", class: "card-img-top") %>
      <div class="card-body" id="accessory-<%= item.id %>">
        <h5 class="card-title"><%= link_to item.title, accessory_path(item.id) %></h5>
      </br>
      <% if item.retired? %>
        <button type="button" class="btn btn-secondary btn-lg" disabled>Retired Accessory</button>
      <% else %>
        <%= button_to 'Add to Cart', carts_path(accessory_id: item.id, do: 'add'), class: "btn btn-primary"%>
      <% end %>
    </br>
      <%= link_to "Edit", edit_admin_accessory_path(item), class: "btn btn-primary" %>


      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/admin/accessories/new.html.erb
<h1 class='text-center'>Create New Accessory</h1>

<%= render partial: "form" %>