config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/bike-shop' => 'accessories#index'

  get '/dashboard' => 'users#dashboard'
  get '/trips-dashboard' => 'trips#dashboard'
  get '/stations-dashboard' => 'stations#dashboard'
  get '/conditions-dashboard' => 'conditions#dashboard'

  delete '/carts' => 'carts#destroy'
  post '/carts' => 'carts#create'
  put '/carts' => 'carts#update'

  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:show, :create]
  resources :carts, only: [:create, :index]
  resources :stations, only: [:index]
  resources :trips, only: [:index, :show]
  resources :conditions, only: [:index, :show]
	resources :accessories, only: :show

  namespace :admin do
    resources :stations, except: [:index, :show]
    resources :trips, except: [:index, :show]
    resources :conditions, except: [:index, :show]
    resources :accessories, only: [:create, :edit, :update]
    resources :orders, only: [:edit, :update]
    get '/dashboard' => 'users#dashboard'
    get '/bike-shop' => 'accessories#index'
    get '/bike-shop/new' => 'accessories#new'
  end

   get '/:id', to: 'stations#show', as: :station
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Hash.new(0)
  end

  def add_accessory(id)
    @contents[id] = @contents[id] ||= 0
    @contents[id] = @contents[id] + 1
  end

  def subtract_accessory(id)
    @contents[id] = @contents[id] - 1 unless @contents[id] <= 0
    destroy_cart_item(id) if @contents[id] == 0
  end

  def destroy_cart_item(id)
    @contents.delete(id.to_s)
  end

  def count_of(id)
    @contents[id].to_i
  end

  def total_count
    @contents.values.sum
  end

  def format
    formatted_hash = {}
    @contents.each do |item_id, count|
      item = Accessory.find(item_id.to_i)
      formatted_hash[item] = {'count' => count, 'subtotal' => (item.price * count)}
    end
    formatted_hash
  end

  def cart_total
    format.values.inject(0) do |init, hash|
      init += hash['subtotal']
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper
  
  def index
    @items = @cart.format
    @total = @cart.cart_total
  end

  def create
    accessory = Accessory.find(params[:accessory_id])
    @cart.add_accessory(accessory.id.to_s)
    session[:cart] = @cart.contents
    quantity = @cart.count_of(accessory.id.to_s)
    flash[:notice] = "You now have #{quantity} of #{accessory.title} in your cart."
    redirect_to bike_shop_path
  end

  def update
    accessory = Accessory.find(params[:accessory_id])
    if params[:do] == 'add'
      @cart.add_accessory(accessory.id.to_s)
    elsif params[:do] == 'subtract'
      @cart.subtract_accessory(accessory.id.to_s)
    end
    session[:cart] = @cart.contents
    quantity = @cart.count_of(accessory.id.to_s)
    flash[:notice] = "You now have #{quantity} of #{accessory.title} in your cart."
    redirect_to carts_path
  end

  def destroy
    accessory = Accessory.find(params[:accessory_id])
    @cart.destroy_cart_item(accessory.id)
    session[:cart] = @cart.contents
    flash[:notice] = "Successfully removed #{view_context.link_to accessory.title, accessory_path(accessory)} from your cart."
    redirect_to carts_path
  end
end

app/views/carts/index.html.erb
<h1>Cart Items</h1>

  <table style="width:100%">
  <tr>
    <th></th>
    <th>Item</th>
    <th></th>
    <th></th>
    <th>Quantity</th>
    <th></th>
    <th>Sub-Total</th>
    <th>Delete</th>
  </tr>
<% @items.each do |item, values_hash| %>
  <tr id="accessory-<%= item.id %>">
    <td><%= image_tag(item.image, :size => "100x67") %>
    <td> <%= item.title %></td>
    <td>Price: <%= item.price %></td>
    <td> <%= button_to '-', carts_path(accessory_id: item.id, do: 'subtract'), method: :put %></td>
    <td>Count: <%= values_hash['count'] %></td>
    <td> <%= button_to '+', carts_path(accessory_id: item.id, do: 'add'), method: :put %></td>
    <td> <%= number_to_currency(values_hash['subtotal'])%></td>
    <td> <%= link_to 'Remove', carts_path(accessory_id: item.id), method: :delete %></td>
  </tr>
<% end %>
<br>
</tr>
  </table>
  <td>Total: <%= number_to_currency(@total) %></td>

<h3><%= link_to "Checkout", orders_path, method: :post %> </h3>