config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/bike-shop' => 'accessories#index'

  get '/dashboard' => 'users#dashboard'
  get '/trips-dashboard' => 'trips#dashboard'
  get '/stations-dashboard' => 'stations#dashboard'
  get '/conditions-dashboard' => 'conditions#dashboard'

  delete '/carts' => 'carts#destroy'
  post '/carts' => 'carts#create'
  put '/carts' => 'carts#update'

  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:show, :create]
  resources :carts, only: [:create, :index]
  resources :stations, only: [:index]
  resources :trips, only: [:index, :show]
  resources :conditions, only: [:index, :show]
	resources :accessories, only: :show

  namespace :admin do
    resources :stations, except: [:index, :show]
    resources :trips, except: [:index, :show]
    resources :conditions, except: [:index, :show]
    resources :accessories, only: [:create, :edit, :update]
    resources :orders, only: [:edit, :update]
    get '/dashboard' => 'users#dashboard'
    get '/bike-shop' => 'accessories#index'
    get '/bike-shop/new' => 'accessories#new'
  end

   get '/:id', to: 'stations#show', as: :station
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :password, require: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
  has_many :orders

  enum role: ['default', 'admin']
end

app/controllers/admin/users_controller.rb
class Admin::UsersController< Admin::BaseController
  def dashboard
    if params[:status].nil?
      @orders = Order.all
    else
      @orders = Order.where(status: params[:status])
    end

    @accessories = Accessory.all
    @ordered_count = Order.where(status: 'Ordered').count
    @paid_count = Order.where(status: 'Paid').count
    @canceled_count = Order.where(status: 'Canceled').count
    @completed_count = Order.where(status: 'Completed').count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:dashboard, :edit, :update]

  def dashboard
    @orders = @user.orders
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user.email.downcase!
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
      flash[:notice] = "Successfully created account for #{@user.name}!"
    else
      flash[:alert] = 'Oops, could not create account. Please use a valid email and password and try again.'
      render :new
    end
  end

  def edit
    if current_user.id.to_s != params[:id]
      render file: "/public/404"
    end
  end

  def update
    @user.update(user_params)
    if @user.save
      flash[:success] = "#{@user.name} profile updated."
      redirect_to dashboard_path
    else
      flash[:failure] = "Please fill in all fields to update user profile."
      redirect_to edit_user_path(@user)
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/views/admin/users/dashboard.html.erb
<h1 class='text-center'>Admin Dashboard</h1>


<h4 class='text-center'>Name: <%= current_user.name %></h4>
<h4 class='text-center'>Current Email: <%= current_user.email %></h4>
<h4 class='text-center'>Current Address: <%= current_user.address %></h4>

<p class='text-center'> <%= link_to 'Edit Profile', edit_user_path(current_user) %></p>

<div class="container">
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-12">
        <h4>Orders by Status</h4>
        <table class="table">
        <tbody>
          <tr>
            <td><%= link_to "Ordered: ", admin_dashboard_path(status: 'Ordered') %><%= @ordered_count %></td>
            <td><%= link_to "Paid: ", admin_dashboard_path(status: 'Paid') %><%= @paid_count %></td>
            <td><%= link_to "Canceled: ", admin_dashboard_path(status: 'Canceled') %><%= @canceled_count%></td>
            <td><%= link_to "Completed: ", admin_dashboard_path(status: 'Completed') %><%= @completed_count%></td>
          </tr>
        </tbody>
      </table>

      <table class="table">
        <thead>
          <tr>
            <th scope="col">Order</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr id="order-<%= order.id %>">
            <td><%= link_to order.id, order_path(order) %></td>
            <td><%= order.status %></td>
            <td><%= link_to "Edit", edit_admin_order_path(order)%></td>
            <% if order.status == "Ordered"%>
              <td><%= link_to "Mark as Paid", admin_order_path(order, {order: {status: "Paid"}}), method: :patch %></td>
              <td><%= link_to "Cancel Order", admin_order_path(order, {order: {status: "Canceled"}}), method: :put %></td>
            <% elsif order.status == "Paid" %>
              <td><%= link_to "Mark as Completed", admin_order_path(order, {order: {status: "Completed"}}), method: :put %></td>
              <td><%= link_to "Cancel Order", admin_order_path(order, {order: {status: "Canceled"}}), method: :put %></td>
            <% end %>
          </tr>
          <% end %>
          </tbody>
        </table>
        <p><%= link_to "Back to All Orders", admin_dashboard_path %></p>
        <h4><%= link_to 'All Accessories', admin_bike_shop_path %></h4>
      </div>
    <div class="col-sm"></div>
  </div>
</div>